### Variables
@baseUrl = http://localhost:8069
@resourcePath = ammunition-types

### Get all ammunition types
GET {{baseUrl}}/{{resourcePath}}
Accept: application/json

### Get ammunition type by ID
GET {{baseUrl}}/{{resourcePath}}/1
Accept: application/json

### Create a new ammunition type
POST {{baseUrl}}/{{resourcePath}}
Content-Type: application/json
Accept: application/json

{
  "caliber": "5.56mm",
  "type": "Sturmgewehr"
}

### Update an ammunition type
PUT {{baseUrl}}/{{resourcePath}}/1
Content-Type: application/json
Accept: application/json

{
  "caliber": "7.62mm",
  "type": "Scharfschützengewehr"
}

### Delete an ammunition type
DELETE {{baseUrl}}/{{resourcePath}}/1
Accept: application/json
